import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mystyle


# ============================================================
# Apply publication style
# ============================================================

mystyle.apply_style()


# ============================================================
# DATA
# ============================================================

# Load all data from the single CSV file.
# Keep the CSV in the same directory as this script.
DATA_FILE = "pipeline_validation_data.csv"

data = pd.read_csv(DATA_FILE)

# Additional validation datasets for supplementary panels.
BASELINE_FILE = "baseline_metrics.csv"
ROI_REPEAT_FILE = "roi_repeatability_metrics.csv"
CONTACT_FILE = "contact_threshold_summary.csv"
# Contact-threshold summary generated by detect_and_track_review_contact_only.py.

baseline = pd.read_csv(BASELINE_FILE)
roi_repeatability = pd.read_csv(ROI_REPEAT_FILE)
contact = pd.read_csv(CONTACT_FILE)


def get_data(metric, method=None):
    """Return noise, value, and error arrays for a metric."""
    df = data[data["metric"] == metric].copy()

    if method is not None:
        df = df[df["method"] == method]

    df = df.sort_values("noise_sigma")

    # Missing values are represented as NaN in the CSV.
    df["value"] = pd.to_numeric(df["value"], errors="coerce")
    df["error"] = pd.to_numeric(df["error"], errors="coerce")

    return (
        df["noise_sigma"].to_numpy(),
        df["value"].to_numpy(),
        df["error"].to_numpy(),
    )


def get_method_data(metric):
    """Return {method: (noise, value)} for a multi-method metric."""
    result = {}

    df = data[data["metric"] == metric].copy()
    df["value"] = pd.to_numeric(df["value"], errors="coerce")

    for method in df["method"].dropna().unique():
        sub = df[df["method"] == method].sort_values("noise_sigma")

        result[method] = (
            sub["noise_sigma"].to_numpy(),
            sub["value"].to_numpy(),
        )

    return result


# ------------------------------------------------------------
# IoU: model comparison
# ------------------------------------------------------------

iou_data = get_method_data("IoU")


# ------------------------------------------------------------
# Downstream validation of selected StarDist pipeline
# ------------------------------------------------------------

noise_precision, daughter_precision, daughter_precision_err = get_data(
    "Daughter precision",
    method="stardist",
)

_, mother_area_error, mother_area_error_err = get_data(
    "Mother area error",
    method="stardist",
)

_, mother_area_agreement, _ = get_data(
    "Mother area agreement",
    method="stardist",
)


# ------------------------------------------------------------
# Supplementary data
# ------------------------------------------------------------

# Mother centroid error
noise_centroid, mother_centroid_error, mother_centroid_error_err = get_data(
    "Mother centroid error",
    method="stardist",
)

# The original CSV contains missing error values for the final two
# centroid-error measurements. Matplotlib cannot plot a partially
# missing yerr array, so use error bars only where an error is available.
centroid_error_mask = np.isfinite(mother_centroid_error_err)


# Hausdorff discrepancy
hausdorff_data = get_method_data("Hausdorff discrepancy")


# Vesicle quantification deviation
vesicle_quantification_data = get_method_data(
    "Vesicle quantification deviation"
)


# ============================================================
# COLORS
# ============================================================

# StarDist is highlighted consistently as the selected model.

stardist_color = "#CC79A7"

# Colour used for the mother-area agreement curve
mother_color = "#0072B2"

method_colors = {
    "watershed":      "#56B4E9",
    "active_contour": "#E69F00",
    "cellpose":       "#009E73",
    "stardist":       stardist_color,
}

method_markers = {
    "watershed": "o",
    "active_contour": "x",
    "cellpose": "s",
    "stardist": "P",
}

method_linestyles = {
    "watershed": "-",
    "active_contour": "--",
    "cellpose": ":",
    "stardist": "--",
}


# ============================================================
# MAIN FIGURE
#
# (a) IoU comparison
# (b) Daughter precision + Mother area agreement
# ============================================================

fig, axes = plt.subplots(
    1, 2,
    figsize=(4.5, 2.2)
)

ax1, ax2 = axes


# ============================================================
# (a) IoU MODEL COMPARISON
# ============================================================

for method, (noise, values) in iou_data.items():

    if method == "stardist":
        linewidth = 2.0
        markersize = 5.5
        alpha = 1.0
        zorder = 5
    else:
        linewidth = 1.2
        markersize = 4.0
        alpha = 0.65
        zorder = 2

    ax1.plot(
        noise,
        values,

        marker=method_markers[method],
        linestyle=method_linestyles[method],

        linewidth=linewidth,
        markersize=markersize,

        color=method_colors[method],
        alpha=alpha,
        zorder=zorder,

        label=method.replace("_", " "),
    )


mystyle.format_axis(
    ax1,
    x_label=r"Noise $\sigma$",
    y_label="Intersection over Union"
)

ax1.set_xlim(-0.05, 1.05)
ax1.set_ylim(-0.02, 0.58)

ax1.set_xticks([0.0, 0.5, 1.0])
ax1.set_yticks(np.arange(0, 0.51, 0.1))

ax1.legend(
    frameon=False,
    fontsize=6.5,
    loc="upper right",
    handlelength=1.8,
)

mystyle.panel_label(ax1, "a", x_offset=0.5, y_offset=1.1)


# ============================================================
# (b) DOWNSTREAM PERFORMANCE
# ============================================================

# ------------------------------------------------------------
# Daughter precision
# ------------------------------------------------------------

ax2.errorbar(
    noise_precision,
    daughter_precision,
    yerr=daughter_precision_err,

    fmt='o-',

    color=stardist_color,
    markerfacecolor=stardist_color,
    markeredgecolor=stardist_color,

    markeredgewidth=1.0,
    linewidth=1.7,
    markersize=4.8,

    capsize=2.5,
    elinewidth=1.1,

    label="Daughter precision",
)


# ------------------------------------------------------------
# Mother area agreement
# ------------------------------------------------------------

ax2.plot(
    noise_precision,
    mother_area_agreement,

    's--',

    color=mother_color,
    markerfacecolor=mother_color,
    markeredgecolor=mother_color,

    linewidth=1.6,
    markersize=4.5,

    label="Mother area agreement",
)


mystyle.format_axis(
    ax2,
    x_label=r"Noise $\sigma$",
    y_label="Performance"
)

ax2.set_xlim(-0.02, 0.52)
ax2.set_ylim(0, 1.05)

ax2.set_xticks(np.arange(0, 0.51, 0.1))
ax2.set_yticks(np.arange(0, 1.01, 0.2))

ax2.legend(
    frameon=False,
    fontsize=6.5,
    loc="upper right",
    handlelength=1.8,
)

mystyle.panel_label(ax2, "b", x_offset=0.5, y_offset=1.1)


# ============================================================
# MAIN FIGURE LAYOUT
# ============================================================

fig.subplots_adjust(
    left=0.09,
    right=0.98,
    bottom=0.22,
    top=0.96,
    wspace=0.38
)

mystyle.save_pdf_png(
    fig,
    "Figure 4"
)

plt.show()


# ============================================================
# SUPPLEMENTARY FIGURE
#
# 2 rows x 3 columns:
# Row 1:
# (a) Mother centroid error
# (b) Hausdorff discrepancy
# (c) Vesicle quantification deviation
#
# Row 2:
# (d) TP / FP / FN object counts from baseline_metrics
# (e) ROI mother-area deviation box plot
# (f) Contact threshold vs contact-finding error
# ============================================================

fig, axes = plt.subplots(
    2, 3,
    figsize=(8.2, 4.8)
)

ax1, ax2, ax3, ax4, ax5, ax6 = axes.ravel()


# ============================================================
# (a) MOTHER CENTROID ERROR
# ============================================================

ax1.plot(
    noise_centroid,
    mother_centroid_error,
    'o-',
    color=stardist_color,
    markerfacecolor=stardist_color,
    markeredgecolor=stardist_color,
    linewidth=1.6,
    markersize=4.5,
)

if np.any(centroid_error_mask):
    ax1.errorbar(
        noise_centroid[centroid_error_mask],
        mother_centroid_error[centroid_error_mask],
        yerr=mother_centroid_error_err[centroid_error_mask],
        fmt='none',
        ecolor=stardist_color,
        capsize=2.5,
        elinewidth=1.1,
    )

mystyle.format_axis(
    ax1,
    x_label=r"Noise $\sigma$",
    y_label="Mother centroid error"
)
ax1.set_xlim(-0.02, 0.52)
ax1.set_ylim(0, 105)
ax1.set_xticks(np.arange(0, 0.51, 0.1))
ax1.set_yticks(np.arange(0, 101, 20))
mystyle.panel_label(ax1, "a")


# ============================================================
# (b) HAUSDORFF DISCREPANCY
# ============================================================

for method, (noise, values) in hausdorff_data.items():
    ax2.plot(
        noise,
        values,
        marker=method_markers[method],
        linestyle=method_linestyles[method],
        linewidth=(2.0 if method == "stardist" else 1.5),
        markersize=(5.2 if method == "stardist" else 4.5),
        color=method_colors[method],
        alpha=(1.0 if method == "stardist" else 0.75),
        label=method.replace("_", " "),
    )

mystyle.format_axis(
    ax2,
    x_label=r"Noise $\sigma$",
    y_label=r"$H_d$ (pixels)"
)
ax2.set_xlim(-0.05, 1.05)
ax2.set_ylim(5, 42)
ax2.set_xticks([0, 0.5, 1.0])
ax2.legend(
    loc="lower right",
    frameon=False,
    fontsize=6.5,
    handlelength=1.8,
)
mystyle.panel_label(ax2, "b")


# ============================================================
# (c) VESICLE QUANTIFICATION DEVIATION
# ============================================================

for method, (noise, values) in vesicle_quantification_data.items():
    ax3.plot(
        noise,
        values,
        marker=method_markers[method],
        linestyle=method_linestyles[method],
        linewidth=(2.0 if method == "stardist" else 1.5),
        markersize=(5.2 if method == "stardist" else 4.5),
        color=method_colors[method],
        alpha=(1.0 if method == "stardist" else 0.75),
        label=method.replace("_", " "),
    )

mystyle.format_axis(
    ax3,
    x_label=r"Noise $\sigma$",
    y_label=r"$\Delta V$"
)
ax3.set_xlim(-0.05, 1.05)
ax3.set_ylim(1.0, 3.6)
ax3.set_xticks([0, 0.5, 1.0])
mystyle.panel_label(ax3, "c")


# ============================================================
# (d) TP / FP / FN OBJECT COUNTS — BASELINE
# ============================================================

# For daughter-object performance, restrict the comparison to frames
# containing at least one ground-truth daughter. This avoids the many
# zero/zero frames dominating the object-count summary.
baseline_objects = baseline[baseline["n_gt_daughters"] > 0].copy()

object_counts = (
    baseline_objects
    .groupby("backend")[["tp_objects", "fp_objects", "fn_objects"]]
    .mean()
    .reindex(["watershed", "active_contour", "cellpose", "stardist"])
)

models = object_counts.index.to_list()
y = np.arange(len(models))

metric_style = {
    "tp_objects": ("TP", "#CC79A7", "o"),
    "fp_objects": ("FP", "#009E73", "s"),
    "fn_objects": ("FN", "#56B4E9", "^"),
}

offsets = [-0.16, 0.0, 0.16]

for (column, (label, color, marker)), offset in zip(
    metric_style.items(), offsets
):
    values = object_counts[column].to_numpy()

    ax4.scatter(
        values,
        y + offset,
        s=34,
        marker=marker,
        facecolors=color,
        edgecolors="white",
        linewidths=0.7,
        zorder=3,
        label=label,
    )

    # Short line from zero to the measured value.
    for yi, value in zip(y + offset, values):
        ax4.plot(
            [0, value],
            [yi, yi],
            color=color,
            linewidth=1.2,
            alpha=0.55,
            zorder=2,
        )

ax4.set_yticks(y)
ax4.set_yticklabels([m.replace("_", " ") for m in models])
ax4.invert_yaxis()

mystyle.format_axis(
    ax4,
    x_label="Mean object count",
    y_label="Model",
)

ax4.set_xlim(left=0)
ax4.legend(
    frameon=False,
    fontsize=6.5,
    loc="lower right",
    ncol=3,
    columnspacing=0.8,
    handletextpad=0.35,
    handlelength=1.0,
)

mystyle.panel_label(ax4, "d")



# ============================================================
# (e) ROI MOTHER AREA ERROR — BOX + REPEATED MEASUREMENTS
# ============================================================

roi_area_error = pd.to_numeric(
    roi_repeatability["mother_area_deviation_percent"],
    errors="coerce",
).dropna().to_numpy()

# Horizontal orientation makes the small spread easier to read.
bp = ax5.boxplot(
    roi_area_error,
    vert=False,
    positions=[1],
    widths=0.36,
    patch_artist=True,
    showfliers=False,
    boxprops=dict(
        facecolor="#CC79A7",
        alpha=0.18,
        edgecolor="#CC79A7",
        linewidth=1.4,
    ),
    medianprops=dict(
        color="#CC79A7",
        linewidth=1.8,
    ),
    whiskerprops=dict(
        color="#CC79A7",
        linewidth=1.2,
    ),
    capprops=dict(
        color="#CC79A7",
        linewidth=1.2,
    ),
)

# Every ROI repeat is shown explicitly.
rng = np.random.default_rng(42)
y_jitter = 1.0 + rng.normal(0, 0.035, len(roi_area_error))

ax5.scatter(
    roi_area_error,
    y_jitter,
    s=28,
    facecolors="white",
    edgecolors="#CC79A7",
    linewidths=1.0,
    zorder=4,
)

# Mean marker.
mean_error = np.mean(roi_area_error)
ax5.scatter(
    [mean_error],
    [1.0],
    marker="D",
    s=32,
    facecolors="#CC79A7",
    edgecolors="white",
    linewidths=0.8,
    zorder=5,
)

mystyle.format_axis(
    ax5,
    x_label="Mother area deviation (%)",
    y_label="",
)

ax5.set_yticks([1])
ax5.set_yticklabels(["ROI repeats"])
ax5.set_ylim(0.65, 1.35)

# Give the small but real repeatability spread enough visual space.
pad = 0.18
ax5.set_xlim(
    roi_area_error.min() - pad,
    roi_area_error.max() + pad,
)

mystyle.panel_label(ax5, "e")



# ============================================================
# (f) CONTACT THRESHOLD — MEAN ± SD
# ============================================================

# Read the contact-threshold summary CSV.
# Expected columns:
#   contact_threshold_px
#   mean_MLS, std_MLS
#   mean_MSS, std_MSS
#   mean_total_contacts, std_total_contacts

contact_summary = pd.read_csv("contact_threshold_summary.csv")

for col in contact_summary.columns:
    contact_summary[col] = pd.to_numeric(
        contact_summary[col], errors="coerce"
    )

contact_summary = contact_summary.sort_values("contact_threshold_px")

thresholds = contact_summary["contact_threshold_px"].to_numpy()

# Plot mean ± standard deviation for total contacts.
mean_total = contact_summary["mean_total_contacts"].to_numpy()
std_total = contact_summary["std_total_contacts"].to_numpy()

ax6.errorbar(
    thresholds,
    mean_total,
    yerr=std_total,
    fmt="o-",
    color=stardist_color,
    markerfacecolor="white",
    markeredgecolor=stardist_color,
    markeredgewidth=1.2,
    linewidth=1.5,
    markersize=5,
    capsize=2.5,
    elinewidth=1.0,
    label="Total contacts",
)

mystyle.format_axis(
    ax6,
    x_label="Contact threshold (pixels)",
    y_label="Mean number of contacts",
)

ax6.set_xticks(thresholds[::2])
ax6.set_ylim(bottom=0)

ax6.legend(
    frameon=False,
    fontsize=6.5,
    loc="upper left",
    handlelength=1.5,
    handletextpad=0.4,
)

mystyle.panel_label(ax6, "f")


# ============================================================
# SUPPLEMENTARY FIGURE LAYOUT
# ============================================================

fig.subplots_adjust(
    left=0.085,
    right=0.985,
    bottom=0.16,
    top=0.96,
    wspace=0.38,
    hspace=0.58,
)

# Final typography pass for the denser 2x3 supplementary layout.
for ax in axes.ravel():
    ax.tick_params(axis="both", which="major", labelsize=7, pad=2)
    ax.tick_params(axis="both", which="minor", length=2.5)
    ax.xaxis.label.set_size(8.5)
    ax.yaxis.label.set_size(8.5)

mystyle.save_pdf_png(
    fig,
    "pipeline_validation_supplementary"
)

plt.show()
